Update pipelines and implement tests
ScholarPack/flask-environment-manager pull request #4
Opened 2021-02-05 15:09 UTC by MKoppJones

- Added tests and enabled them in the pipelines
- Added mypy to pipeline
- Updated comparison method to pretty print a table. This is **intended** to be a dev feature, only use if while getting set up with SSM.
- Fix some small bugs that arose during tests.
- Add typing
- Update setup for pypi

Still to do
- Allow flask config for connection to AWS. It currently needs to be set at the OS env level.
- Update the README

2021-02-05 15:11 UTC, CoburnJoe commented on .github/workflows/main.yml
> +        pytest tests
Line 35 is redundant - line 38 will run the tests as well as calculate the coverage :)

2021-02-05 15:14 UTC, CoburnJoe commented on flask_environment_manager/environment_manager.py
> +        print(table)
Not sure how well this will translate in AWS land

2021-02-05 15:15 UTC, CoburnJoe commented on tests/test_config.py
> +    @pytest.mark.parametrize(
Tests look comprehensive 👍

2021-02-05 15:15 UTC, CoburnJoe submitted a review, later dismissed

2021-02-05 15:25 UTC, nomad-software requested changes

2021-02-05 15:25 UTC, nomad-software commented on flask_environment_manager/environment_manager.py
> +from termcolor import colored, cprint
Personally I wouldn't have any colouring in the output. ANSI escape codes are not handled well in some circumstances.

2021-02-05 15:25 UTC, nomad-software commented on flask_environment_manager/environment_manager.py
> +        print(table)
Yeah, the only output must only be to the log.

2021-02-05 15:49 UTC, MKoppJones commented on flask_environment_manager/environment_manager.py
> +from termcolor import colored, cprint
This has been removed, as discussed on slack.

2021-02-05 15:49 UTC, MKoppJones commented on flask_environment_manager/environment_manager.py
> +        print(table)
Colors have been removed and print has been swapped to use the app logger

2021-02-05 15:50 UTC, MKoppJones commented on .github/workflows/main.yml
> +        pytest tests
Updated

2021-02-05 16:03 UTC, CoburnJoe submitted a review, later dismissed

2021-02-08 08:46 UTC, swiftace commented on tests/test_config.py
> +        ],
It'd be good to include string variants of `("true", True)`.

2021-02-08 09:24 UTC, swiftace submitted a review, later dismissed

2021-02-08 09:40 UTC, CoburnJoe commented on setup.py
> +    install_requires=["flask", "boto3", "beautifultable", "termcolor"],
Is `termcolor` still required here?

2021-02-08 09:41 UTC, MKoppJones commented on setup.py
> +    install_requires=["flask", "boto3", "beautifultable", "termcolor"],
Nope!

Will remove

2021-02-08 09:46 UTC, CoburnJoe approved these changes

2021-02-08 09:48 UTC, swiftace approved these changes

2021-02-08 10:06 UTC, nomad-software approved these changes

2021-02-08 10:07 UTC, merged