Support multiple paths in the SSM Environment Manager
ScholarPack/flask-environment-manager pull request #7
Opened 2021-02-16 10:57 UTC by MKoppJones

This change will allow a list of paths to be provided and will load all the variables into one dict.

Any clashing parameters will be overwritten with the last path used being the one that is kept.

I am really interested in reviews around the SsmEnvironmentManager constructor and my handling of the possible non-list. Is this pythonic? Is the okay? Suggestions?

**Pytest Changes**
Now, instead of generating a new client in the test, we generate it as part of the pytest fixtures and mock it in the tests we want to use it in. This is okay as we will only ever be reading from boto3, not writing.

2021-02-16 11:09 UTC, nomad-software requested changes

2021-02-16 11:09 UTC, nomad-software commented on flask_environment_manager/ssm_environment_manager.py
> +        self._path: list = []
Variable name should probably be plural here.

2021-02-16 11:09 UTC, nomad-software commented on flask_environment_manager/ssm_environment_manager.py
> +        ssm = self._get_values_from_paths()
Give the `ssm` variable a better name.

2021-02-16 11:09 UTC, nomad-software commented on flask_environment_manager/ssm_environment_manager.py
> +        """
I would maybe add a little more context to the comment here about the information being collected into the dict. Also, i'm assuming there are also keys being collected too, not just values so perhaps the name could be made more clear?

2021-02-16 11:09 UTC, nomad-software commented on flask_environment_manager/ssm_environment_manager.py
> +        return ssm
Is there a better name than `ssm` here?

2021-02-16 11:11 UTC, nomad-software commented on flask_environment_manager/ssm_environment_manager.py
> +        path: Optional[Union[str, list]] = [],
I would probably just make this a list for simplicity sake.

2021-02-16 11:55 UTC, MKoppJones commented on flask_environment_manager/ssm_environment_manager.py
> +        """
Not sure why this has not been marked as outdated, however, this has been updated to be more contextual 👍

2021-02-16 13:06 UTC, nomad-software submitted a review, later dismissed

2021-02-16 13:13 UTC, nomad-software approved these changes

2021-02-17 08:18 UTC, CoburnJoe approved these changes

2021-02-17 09:45 UTC, merged